### ISSUE TITLE
PyTorch dataset class

### ISSUE THREAD

**Issue by mpariente** [facebookresearch/EasyComDataset#1]
Hello, 

Thanks for open-sourcing this great dataset ! 

Would it be possible to share a PyTorch `Dataset` class that handles the preprocessing of the data and the data loading? That would make working with the dataset very straightforward !

Thanks, 
Manu

**Comment by jdonley** [comment]
Hi Manu,
Thanks for your interest and question. I will ask around and see if we can provide something.
If you're open to it, you're also welcome to submit one via a pull request after reading and following [`CONTRIBUTING.md`](https://github.com/facebookresearch/EasyComDataset/blob/main/CONTRIBUTING.md). :)

**Comment by mpariente** [comment]
Hey Jacob, 

Thanks for your answer ! I'll wait a bit to find out if you can provide something, then, I'm sure you have a great dataset class that would make me gain a little time :wink: 
If you can't share anything, I'll end up writing my own class, and sure, I'll be happy to make a PR to integrate it !

**Comment by jdonley** [comment]
Hi Manu, after asking around, it may be simpler and easier for you to implement one. We don't want to hold you back. If you have any questions while writing a class, we'd be happy to answer. 🙂
