### ISSUE TITLE
keep geting unexpected end of file

### ISSUE THREAD

**Issue by EranGilead** [facebookresearch/EasyComDataset#3]
Hi there,

I'm trying to get your dataset for linux and receiving  gzip: stdin: unexpected end of file
![image](https://user-images.githubusercontent.com/62499631/152683071-34ab44bd-24e4-4e7c-b411-880678eccb56.png)

Do you know the reason?

**Comment by tateemma** [comment]
I am getting "unexpected end of file" and "is not archive" errors on Windows. How can I solve this?
