### ISSUE TITLE
I am getting "unexpected end of archive", "cannot open as archive" and "is not archive" errors on Windows. How can I solve this?

### ISSUE THREAD

**Issue by tateemma** [facebookresearch/EasyComDataset#4]
<img width="299" alt="Screenshot 2022-07-27 012710" src="https://user-images.githubusercontent.com/22529690/181129138-6c9b0b0d-2e49-4af0-ad4f-68ab1760c51a.png">

**Comment by jdonley** [comment]
Hi @tateemma, each file is part of a larger archive. The scripts included on the releases page should work for downloading each part and then extracting the dataset.
Which of the two scripts have you run?
If neither, could you give them a try and let me know if you still encounter errors?

**Comment by tateemma** [comment]
I ran the script for windows. I've attached the errors I got.
<img width="674" alt="easycom screenshot 1" src="https://user-images.githubusercontent.com/22529690/185203909-78dabc14-f139-4d6c-9cf8-1c779e18901e.png">
<img width="945" alt="easycom screenshot 5" src="https://user-images.githubusercontent.com/22529690/185203899-852bb0bd-12ad-450c-a916-63717063d5d8.png">
<img width="671" alt="easycom screenshot 4" src="https://user-images.githubusercontent.com/22529690/185203904-9693ba59-cbb8-49d3-b08f-857d1bcf8d24.png">
<img width="671" alt="easycom screenshot 3" src="https://user-images.githubusercontent.com/22529690/185203906-318bea3d-99ef-457e-88c7-f2f8abdf2810.png">

The following screenshot shows the only files that are in the folder at the end. When I try to extract them individually, I get errors as shown in the first description of the issue.
<img width="550" alt="easycom screenshot 2" src="https://user-images.githubusercontent.com/22529690/185203907-209bfe05-383a-4dcf-9922-8846ebcb3b80.png">

**Comment by tateemma** [comment]
The screenshot of files shows the only files that are in the folder. And when I try to extract them individually, I get errors as shown in the first description of the issue.

**Comment by jdonley** [comment]
Hi @tateemma, could you please try deleting the existing downloaded parts and trying again? Please also check that your internet connection is stable. If the download fails on one of the parts then the rest of the script will fail to extract the contents, which is what appears to be happening.

In the meantime, I can look at adding better error handling for cases where an individual archive-part download fails.

**Comment by jdonley** [comment]
Hi @tateemma, I updated the download script for Windows. It will now retry the download up to 10 times per archive part if it fails. Hopefully this will help if there is a transient error during the download of the archive or even if the error is a temporary one. If a single archive part fails to download after 10 retries, the script will still fail. It will no longer attempt to extract the archive contents if it fails.

Let me know how this works out for you.

**Comment by tateemma** [comment]
The new script is working, thank you. Is there a way to download a subset of the dataset? It seems to require more than 100GB disk space, so it's only stopping after merging the files because I only have about 100GB free space and all of it is being used up before all the files are extracted.

**Comment by tateemma** [comment]
Managed to delete the other downloaded files in the folder and extracted from the remaining ones. I got an error but the good thing is I managed to view some of the data.

**Comment by jdonley** [comment]
Hi @tateemma, if you are running out of space when downloading and extracting the files, you can try and download only a few parts at a time and extract just those. You can do this by running the copy command under the "Merging parts" part of the script and then run extraction command under the "Extracting contents" part of the script after you have downloaded the subset. Then delete the archive parts, download another subset and repeat.

The main downside to this is that the end of each archive-part is not guaranteed to have a complete file that can be extracted correctly. So there will be errors in the extraction process. You may have to check for this and separately re-download/re-extract those files that failed.

**Comment by tateemma** [comment]
Alright. Thank you.
