### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by catherine-qian** [facebookresearch/EasyComDataset#5]
Dear authors,

Thanks for the nice work!
I wonder whether the source code & evaluation methods described in the paper will be publically available or not?

**Comment by jdonley** [comment]
Hi @catherine-qian, at this point in time we are unable to make the source code for the evaluation and methods available. We hope to eventually do so, however, we do not currently have a time frame for this.

If you have any questions regarding the evaluation and/or methods, I am happy to try answer them.
