### ISSUE TITLE
Device_ATF vs. Device_ATF_v2?

### ISSUE THREAD

**Issue by Chutlhu** [facebookresearch/EasyComDataset#8]
Dear EasyCom team,
thank you very much for your nice dataset.

I am working on you ATFs measurements. I just realized that there are two h5 files:
`Device_ATF.h5` and `Device_ATF_v5.h5`.
In the former, the coordinates looks distributed on a regular uniform 2D mesh, while in the latter, the distribution along the elevation axis is non-uniform. 
Could you provide some more details about this? Did you simply collected new measuments?

Cheers,
Diego

**Comment by jdonley** [comment]
Hi Diego,
These two files are created from measurements made by two different physical systems, hence the minor differences in the coordinate positions.
